# Generated by Django 5.1.2 on 2024-10-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
