# Generated by Django 5.1.2 on 2024-10-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_user_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True),
        ),
    ]
