# Generated by Django 5.1.2 on 2024-11-07 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="product_detail_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="store.productdetail",
            ),
        ),
    ]
