# Generated by Django 5.1.2 on 2024-11-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_productimage_product_detail_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="quantity",
            field=models.IntegerField(default=20, null=True),
        ),
    ]
