# Generated by Django 5.1.2 on 2024-11-07 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_productdetail_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="product_detail_id",
        ),
    ]
