# Generated by Django 5.1.2 on 2024-11-07 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_remove_productimage_product_detail_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="product_detail_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images_2",
                to="store.productdetail",
            ),
        ),
    ]
